### ISSUE TITLE
Better documentation & guide

### ISSUE THREAD

**Issue by stavlocker** [mattimustang/wadofstuff#29]
Hi guys.
This seems like a really neat idea and exactly what I need but I'm going back and forth through the source code just to figure out how to use it.
The README.md should have a guide to install & use with full code including imports.

On a related note, which modules should I import to use it?

EDIT: When importing json (`from wadofstuff.django.serializers import json`) I get an `ImportError: cannot import name 'simplejson'`. Why?

**Comment by ghost** [comment]
Hi, if you are using Django 2, then use this. Its working fine for me.
https://github.com/hasahmad/wadofstuff-django-serializers

**Comment by mattimustang** [comment]
Hi, I no longer maintain this code. It is here for archival purposes only. However, do check out my blog articles on how to use it

https://wadofstuff.blogspot.com/search/label/serializer

**Comment by shayneoneill** [comment]
@mattimustang maybe consider adding a note to the front page pointing them at the fork. Wadofstuff serializer filled a pretty big for me , and its a pretty great alternative to folks who want to do quick endpoints without the headaches and bureacracy that DRF requires (And dont get me wrong DRF is phenomenal, but its big and moody and requires bit of a commitment to get behaving in a friendly manner). Your serializer did at least a subset of tht work in a single line of code.
